### ISSUE TITLE
Allow players to use enemy vehicles

### ISSUE THREAD

**Issue by VexA3** [7Cav/7Cav_FullSpectrum_V4.Altis#14]
SPM_MissionAdvance_Complete in missionAdvancePreInit is where a transport is unlocked for players to use

ServerPreInit has SERVER_InitializeObject which makes all vics locked. We can change this if required but all vehicles end up despawning at the end of the AO anyways.

**Comment by BojanOnTheInternet** [comment]
Players can get into some vehicles and shoot shit with them. We can manage what vics they can use with the vehicle permissions
