### ISSUE TITLE
Extend night to 2hrs, add command to suspend time accel

### ISSUE THREAD

**Issue by Robot-Panda15** [7Cav/7Cav_FullSpectrum_V4.Altis#185]
Time acceleration is still enabled for night, let's see if we can remove that.

**Comment by BojanOnTheInternet** [comment]
Are you sure we want to remove this? People complain already for having 1 hour of nighttime, I cant imagine it'll go over well if we had maps stuck on nighttime the entire time the map is active. Perhaps a command to disable acceleration temporarily for night MCCs is a better solution.

**Comment by Robot-Panda15** [comment]
yeah option two sounds better. can we extend night out to 2 hours by chance?
