### ISSUE TITLE
Blacklist Dead Man Switch

### ISSUE THREAD

**Issue by Robot-Panda15** [7Cav/7Cav_FullSpectrum_V4.Altis#193]
Not useful in any capacity and will be an attempt to stop trolling

**Comment by Kalthramis** [comment]
Should be easy to remove from the ACE arsenal with just the following in the box's init line, or wheverever we add arsenal to boxes:

`[this, ["ACE_DeadManSwitch"]] call ace_arsenal_fnc_removeVirtualItems`

Alternatively, we could add an eventHandler to players to locally check their items after closing their inventory, and remove it.

**Comment by Robot-Panda15** [comment]
Lets go for the latter option
