### ISSUE TITLE
Allow click to drop boxes in base

### ISSUE THREAD

**Issue by BojanOnTheInternet** [7Cav/7Cav_FullSpectrum_V4.Altis#44]
Right now you get the "dont shoot on base" message

**Comment by VexA3** [comment]
Using the scroll wheel to navigate, then pushing the scroll wheel button down should be the needed fix for this.

**Comment by BojanOnTheInternet** [comment]
Probably add a check in CLIENT_ForceDryFireFiredHandler in clientPreInit and check if the player is carrying a box. There is probably an ACE variable (probably something like ace_dragging_isCarrying) set for the player that we can check. I'll deal with this on monday
